# Generated by Django 4.0.1 on 2022-01-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panstwo', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_instalacji', models.BooleanField(default=False)),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=25)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('rok_wydania', models.DateField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ograniczenia_wiekowe', models.CharField(choices=[('Pegi-3', 'Pegi-3'), ('Pegi-7', 'Pegi-7'), ('Pegi-12', 'Pegi-12'), ('Pegi-16', 'Pegi-16'), ('Pegi-18', 'Pegi-18')], max_length=200)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('ocena', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jezyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SklepGier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('gra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gra')),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=50)),
                ('aktywny', models.BooleanField(default=False)),
                ('data_utworzenia_konta', models.DateField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('adres_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.adres')),
                ('biblioteka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.biblioteka')),
            ],
        ),
        migrations.CreateModel(
            name='Zakup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zakupu', models.DateField()),
                ('return_date', models.DateField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('sklep_gier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sklepgier')),
                ('uzytkownik_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_platnosci', models.DateField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='GraText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('gra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gra')),
            ],
        ),
        migrations.AddField(
            model_name='gra',
            name='jezyk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.jezyk'),
        ),
        migrations.CreateModel(
            name='GatunekGry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('gatunek_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gatunek')),
                ('gra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gra')),
            ],
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='gra_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gra'),
        ),
    ]
