# Generated by Django 4.0.1 on 2022-01-24 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('rok_zalozenia', models.DateField()),
                ('siedziba', models.CharField(max_length=45)),
                ('ilosc_czlonkow', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=50)),
                ('aktywny', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=20)),
                ('opis', models.CharField(max_length=20)),
                ('pegi', models.CharField(max_length=20)),
                ('ocena', models.CharField(max_length=20)),
                ('rok_produkcji', models.DateField()),
                ('idGatunku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.gatunek')),
                ('idProducenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.producent')),
                ('idUzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.uzytkownik')),
            ],
        ),
    ]
