# Generated by Django 4.0.1 on 2022-01-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producent',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='gra',
            name='opis',
            field=models.CharField(max_length=200),
        ),
    ]
