# Generated by Django 4.0.1 on 2022-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_uzytkownik_options_alter_uzytkownik_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gra',
            name='cena',
            field=models.FloatField(blank=True, default=0, verbose_name='Cena za potrawe'),
        ),
        migrations.AddField(
            model_name='gra',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Zdjęcie'),
        ),
    ]
