# Generated by Django 4.0.1 on 2022-01-27 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gra_cena_gra_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gra',
            name='cena',
            field=models.FloatField(blank=True, default=0, verbose_name='Cena Gry'),
        ),
        migrations.AlterField(
            model_name='gra',
            name='idGatunku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.gatunek'),
        ),
        migrations.AlterField(
            model_name='gra',
            name='idProducenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.producent'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Imię i Nazwisko')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Adres')),
                ('address_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Ilosc')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gra')),
            ],
        ),
    ]
