# Generated by Django 4.0.1 on 2022-01-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_gra_cena_alter_gra_idgatunku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gra',
            old_name='tytul',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gra',
            old_name='cena',
            new_name='price',
        ),
    ]
